import logo from "../../../public/doge.2214a63a.svg";
import Image from 'next/image';
import Link from "next/link";
export const metadata = {
    title: 'home',
    description: 'Generated by create next app',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
        <nav class="bg-slate-50 border-2 border-gray-200 px-2 sm:px-4 py-2.5 rounded">
            <div class="container flex flex-wrap items-center justify-between mx-auto">
            <Link href="/home" class="flex items-center">
                <Image src={logo} height={50} width={50}></Image>
                <span class="self-center text-xl font-semibold text-pink-400 mx-3">DogeBlog</span>
            </Link>
            <ul className="flex align-middle">
              <li className="p-3"><Link className="self-center text-right text-lg font-medium text-pink-500" href="/addpost">
              Add post
              </Link></li>
              <li className="p-3"> <Link className="self-center text-right text-lg font-medium text-pink-500" href="/myaccount">
              My Account</Link></li>
            </ul>
            </div>      
        </nav>
        {children}
        </body>
      </html>
    )
  }